### Importing all necessary libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings ('ignore')

#### Loading the Data set: We have 113937 rows × 81 columns

In [2]:
df=pd.read_csv("prosperLoanData.csv")
df.head()

,ListingKey,ListingNumber,ListingCreationDate,CreditGrade,Term,LoanStatus,ClosedDate,BorrowerAPR,BorrowerRate,LenderYield,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,193129,2007-08-26 19:09:29.263000000,C,36,Completed,2009-08-14 00:00:00,0.16516,0.1580,0.1380,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,1209647,2014-02-27 08:28:07.900000000,NaN,36,Current,NaN,0.12016,0.0920,0.0820,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,81716,2007-01-05 15:00:47.090000000,HR,36,Completed,2009-12-17 00:00:00,0.28269,0.2750,0.2400,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,658116,2012-10-22 11:02:35.010000000,NaN,36,Current,NaN,0.12528,0.0974,0.0874,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,909464,2013-09-14 18:38:39.097000000,NaN,36,Current,NaN,0.24614,0.2085,0.1985,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20

#### Statistical Information

In [3]:
df.shape

(113937, 81)

In [4]:
df.dtypes

ListingKey                      object
ListingNumber                    int64
ListingCreationDate             object
CreditGrade                     object
Term                             int64
                                ...
PercentFunded                  float64
Recommendations                  int64
InvestmentFromFriendsCount       int64
InvestmentFromFriendsAmount    float64
Investors                        int64
Length: 81, dtype: object

In [5]:
df.describe()

,ListingNumber,Term,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
count,1.139370e+05,113937.000000,113912.000000,113937.000000,113937.000000,84853.000000,84853.000000,84853.000000,84853.000000,84853.000000,...,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000,113937.000000
mean,6.278857e+05,40.830248,0.218828,0.192764,0.182701,0.168661,0.080306,0.096068,4.072243,5.950067,...,-54.725641,-14.242698,700.446342,681.420499,25.142686,0.998584,0.048027,0.023460,16.550751,80.475228
std,3.280762e+05,10.436212,0.080364,0.074818,0.074516,0.068467,0.046764,0.030403,1.673227,2.376501,...,60.675425,109.232758,2388.513831,2357.167068,275.657937,0.017919,0.332353,0.232412,294.545422,103.239020
min,4.000000e+00,12.000000,0.006530,0.000000,-0.010000,-0.182700,0.004900,-0.182700,1.000000,1.000000,...,-664.870000,-9274.750000,-94.200000,-954.550000,0.000000,0.700000,0.000000,0.000000,0.000000,1.000000
25%,4.009190e+05,36.000000,0.156290,0.134000,0.124200,0.115670,0.042400,0.074080,3.000000,4.000000,...,-73.180000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000
50%,6.005540e+05,36.000000,0.209760,0.184000,0.173000,0.161500,0.072400,0.091700,4.000000,6.000000,...,-34.440000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,44.000000
75%,8.926340e+05,36.000000,0.283810,0.250000,0.240000,0.224300,0.112000,0.116600,5.000000,8.000000,...,-13.920000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,115.000000
max,1.255725e+06,60.000000,0.512290,0.497500,0.492500,0.319900,0.366000,0.283700,7.000000,11.000000,...,32.060000,0.000000,25000.000000,25000.000000,21117.900000,1.012500,39.000000,33.000000,25000.000000,1189.000000

#### Checking Data type of Attributes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 81 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingNumber                        113937 non-null  int64
 2   ListingCreationDate                  113937 non-null  object
 3   CreditGrade                          28953 non-null   object
 4   Term                                 113937 non-null  int64
 5   LoanStatus                           113937 non-null  object
 6   ClosedDate                           55089 non-null   object
 7   BorrowerAPR                          113912 non-null  float64
 8   BorrowerRate                         113937 non-null  float64
 9   LenderYield                          113937 non-null  float64
 10  EstimatedEffectiveYield              84853 non-null   float64
 11  EstimatedLoss                        84853 non-null   float64
 12  EstimatedReturn                      84853 non-null   float64
 13  ProsperRating (numeric)              84853 non-null   float64
 14  ProsperRating (Alpha)                84853 non-null   object
 15  ProsperScore                         84853 non-null   float64
 16  ListingCategory (numeric)            113937 non-null  int64
 17  BorrowerState                        108422 non-null  object
 18  Occupation                           110349 non-null  object
 19  EmploymentStatus                     111682 non-null  object
 20  EmploymentStatusDuration             106312 non-null  float64
 21  IsBorrowerHomeowner                  113937 non-null  bool
 22  CurrentlyInGroup                     113937 non-null  bool
 23  GroupKey                             13341 non-null   object
 24  DateCreditPulled                     113937 non-null  object
 25  CreditScoreRangeLower                113346 non-null  float64
 26  CreditScoreRangeUpper                113346 non-null  float64
 27  FirstRecordedCreditLine              113240 non-null  object
 28  CurrentCreditLines                   106333 non-null  float64
 29  OpenCreditLines                      106333 non-null  float64
 30  TotalCreditLinespast7years           113240 non-null  float64
 31  OpenRevolvingAccounts                113937 non-null  int64
 32  OpenRevolvingMonthlyPayment          113937 non-null  float64
 33  InquiriesLast6Months                 113240 non-null  float64
 34  TotalInquiries                       112778 non-null  float64
 35  CurrentDelinquencies                 113240 non-null  float64
 36  AmountDelinquent                     106315 non-null  float64
 37  DelinquenciesLast7Years              112947 non-null  float64
 38  PublicRecordsLast10Years             113240 non-null  float64
 39  PublicRecordsLast12Months            106333 non-null  float64
 40  RevolvingCreditBalance               106333 non-null  float64
 41  BankcardUtilization                  106333 non-null  float64
 42  AvailableBankcardCredit              106393 non-null  float64
 43  TotalTrades                          106393 non-null  float64
 44  TradesNeverDelinquent (percentage)   106393 non-null  float64
 45  TradesOpenedLast6Months              106393 non-null  float64
 46  DebtToIncomeRatio                    105383 non-null  float64
 47  IncomeRange                          113937 non-null  object
 48  IncomeVerifiable                     113937 non-null  bool
 49  StatedMonthlyIncome                  113937 non-null  float64
 50  LoanKey                              113937 non-null  object
 51  TotalProsperLoans                    22085 non-null   float64
 52  TotalProsperPaymentsBilled           22085 non-null   float64
 53  OnTimeProsperPayments                22085 non-null   float64
 54  ProsperPaymentsLessThanOneMonthLate  22085 non-null   float64
 55  ProsperPaymentsOneMonthPlusLate      22085 non-null   float64
 56  ProsperPrincipalBorrowed             22085 non-null   float64
 57  ProsperPrincipalOutstanding          22085 non-null   float64
 58  ScorexChangeAtTimeOfListing          18928 non-null   float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        16952 non-null   float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  LoanOriginationDate                  113937 non-null  object
 65  LoanOriginationQuarter               113937 non-null  object
 66  MemberKey                            113937 non-null  object
 67  MonthlyLoanPayment                   113937 non-null  float64
 68  LP_CustomerPayments                  113937 non-null  float64
 69  LP_CustomerPrincipalPayments         113937 non-null  float64
 70  LP_InterestandFees                   113937 non-null  float64
 71  LP_ServiceFees                       113937 non-null  float64
 72  LP_CollectionFees                    113937 non-null  float64
 73  LP_GrossPrincipalLoss                113937 non-null  float64
 74  LP_NetPrincipalLoss                  113937 non-null  float64
 75  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 76  PercentFunded                        113937 non-null  float64
 77  Recommendations                      113937 non-null  int64
 78  InvestmentFromFriendsCount           113937 non-null  int64
 79  InvestmentFromFriendsAmount          113937 non-null  float64
 80  Investors                            113937 non-null  int64
dtypes: bool(3), float64(50), int64(11), object(17)
memory usage: 68.1+ MB

#### Checking Unique values in dataset :

In [7]:
df.apply(lambda x: len(x.unique()))

ListingKey                     113066
ListingNumber                  113066
ListingCreationDate            113064
CreditGrade                         9
Term                                3
                                ...
PercentFunded                     719
Recommendations                    17
InvestmentFromFriendsCount         14
InvestmentFromFriendsAmount       726
Investors                         751
Length: 81, dtype: int64

#### Checking duplicate values:

In [8]:
df.duplicated().sum()

0

#### We observe that dataset contains no duplicate values.

#### Checking Missing (null) values:

In [9]:
df.isnull().sum()

ListingKey                         0
ListingNumber                      0
ListingCreationDate                0
CreditGrade                    84984
Term                               0
                               ...
PercentFunded                      0
Recommendations                    0
InvestmentFromFriendsCount         0
InvestmentFromFriendsAmount        0
Investors                          0
Length: 81, dtype: int64

#### We observe  that many attributes have missing values.

#### We have Categorical as well as numerical attributes which we will process seperately.

In [10]:
categorical=df.select_dtypes("object")
categorical

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,DateCreditPulled,FirstRecordedCreditLine,IncomeRange,LoanKey,LoanOriginationDate,LoanOriginationQuarter,MemberKey
0,1021339766868145413AB3B,2007-08-26 19:09:29.263000000,C,Completed,2009-08-14 00:00:00,NaN,CO,Other,Self-employed,NaN,2007-08-26 18:41:46.780000000,2001-10-11 00:00:00,"$25,000-49,999",E33A3400205839220442E84,2007-09-12 00:00:00,Q3 2007,1F3E3376408759268057EDA
1,10273602499503308B223C1,2014-02-27 08:28:07.900000000,NaN,Current,NaN,A,CO,Professional,Employed,NaN,2014-02-27 08:28:14,1996-03-18 00:00:00,"$50,000-74,999",9E3B37071505919926B1D82,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4
2,0EE9337825851032864889A,2007-01-05 15:00:47.090000000,HR,Completed,2009-12-17 00:00:00,NaN,GA,Other,Not available,783C3371218786870A73D20,2007-01-02 14:09:10.060000000,2002-07-27 00:00:00,Not displayed,6954337960046817851BCB2,2007-01-17 00:00:00,Q1 2007,5F7033715035555618FA612
3,0EF5356002482715299901A,2012-10-22 11:02:35.010000000,NaN,Current,NaN,A,GA,Skilled Labor,Employed,NaN,2012-10-22 11:02:32,1983-02-28 00:00:00,"$25,000-49,999",A0393664465886295619C51,2012-11-01 00:00:00,Q4 2012,9ADE356069835475068C6D2
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097000000,NaN,Current,NaN,D,MN,Executive,Employed,NaN,2013-09-14 18:38:44,2004-02-20 00:00:00,"$100,000+",A180369302188889200689E,2013-09-20 00:00:00,Q3 2013,36CE356043264555721F06C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,E6D9357655724827169606C,2013-04-14 05:55:02.663000000,NaN,Current,NaN,C,IL,Food Service Management,Employed,NaN,2013-04-14 05:54:58,1997-09-01 00:00:00,"$50,000-74,999",9BD7367919051593140DB62,2013-04-22 00:00:00,Q2 2013,2EC435768441332602FDC15
113933,E6DB353036033497292EE43,2011-11-03 20:42:55.333000000,NaN,FinalPaymentInProgress,NaN,A,PA,Professional,Employed,NaN,2011-11-03 20:42:53,1992-01-17 00:00:00,"$75,000-99,999",62D93634569816897D5A276,2011-11-07 00:00:00,Q4 2011,55C4336679182766893E4FC
113934,E6E13596170052029692BB1,2013-12-13 05:49:12.703000000,NaN,Current,NaN,D,TX,Other,Employed,NaN,2013-12-13 05:49:15,2002-02-25 00:00:00,"$25,000-49,999",DD1A370200396006300ACA0,2013-12-23 00:00:00,Q4 2013,0FE0370029359765342FDB5
113935,E6EB3531504622671970D9E,2011-11-14 13:18:26.597000000,NaN,Completed,2013-08-13 00:00:00,C,GA,Food Service,Full-time,NaN,2011-11-14 13:18:24,1993-12-01 00:00:00,"$25,000-49,999",589536350469116027ED11B,2011-11-21 00:00:00,Q4 2011,A33834861822272782621C8
113936,E6ED3600409833199F711B7,2014-01-15 09:27:37.657000000,NaN,Current,NaN,A,NY,Professor,Employed,NaN,2014-01-15 09:27:40,1995-01-01 00:00:00,"$50,000-74,999",00AF3704550953269A64E40,2014-01-21 00:00:00,Q1 2014,CE1E3704648000761C9F724

In [11]:
continuous=df.select_dtypes("number")
continuous

,ListingNumber,Term,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,193129,36,0.16516,0.1580,0.1380,NaN,NaN,NaN,NaN,NaN,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,1209647,36,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,7.0,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,81716,36,0.28269,0.2750,0.2400,NaN,NaN,NaN,NaN,NaN,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,658116,36,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,9.0,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,909464,36,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,4.0,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,753087,36,0.22354,0.1864,0.1764,0.16490,0.0699,0.09500,4.0,5.0,...,-75.58,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
113933,537216,36,0.13220,0.1110,0.1010,0.10070,0.0200,0.08070,6.0,8.0,...,-30.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,22
113934,1069178,60,0.23984,0.2150,0.2050,0.18828,0.1025,0.08578,3.0,3.0,...,-16.91,0.0,0.0,0.0,0.0,1.0,0,0,0.0,119
113935,539056,60,0.28408,0.2605,0.2505,0.24450,0.0850,0.15950,4.0,5.0,...,-235.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,274
113936,1140093,36,0.13189,0.1039,0.0939,0.09071,0.0299,0.06081,6.0,7.0,...,-1.70,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

Checking Missing (null) values of Categorical attributes:

In [12]:
categorical.isna().sum()

ListingKey                      0
ListingCreationDate             0
CreditGrade                 84984
LoanStatus                      0
ClosedDate                  58848
ProsperRating (Alpha)       29084
BorrowerState                5515
Occupation                   3588
EmploymentStatus             2255
GroupKey                   100596
DateCreditPulled                0
FirstRecordedCreditLine       697
IncomeRange                     0
LoanKey                         0
LoanOriginationDate             0
LoanOriginationQuarter          0
MemberKey                       0
dtype: int64

#### Filling Missing values of categorical attributes using Mode funcion:

In [13]:
categorical=categorical.fillna(categorical.mode().iloc[0])
categorical

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,DateCreditPulled,FirstRecordedCreditLine,IncomeRange,LoanKey,LoanOriginationDate,LoanOriginationQuarter,MemberKey
0,1021339766868145413AB3B,2007-08-26 19:09:29.263000000,C,Completed,2009-08-14 00:00:00,C,CO,Other,Self-employed,783C3371218786870A73D20,2007-08-26 18:41:46.780000000,2001-10-11 00:00:00,"$25,000-49,999",E33A3400205839220442E84,2007-09-12 00:00:00,Q3 2007,1F3E3376408759268057EDA
1,10273602499503308B223C1,2014-02-27 08:28:07.900000000,C,Current,2014-03-04 00:00:00,A,CO,Professional,Employed,783C3371218786870A73D20,2014-02-27 08:28:14,1996-03-18 00:00:00,"$50,000-74,999",9E3B37071505919926B1D82,2014-03-03 00:00:00,Q1 2014,1D13370546739025387B2F4
2,0EE9337825851032864889A,2007-01-05 15:00:47.090000000,HR,Completed,2009-12-17 00:00:00,C,GA,Other,Not available,783C3371218786870A73D20,2007-01-02 14:09:10.060000000,2002-07-27 00:00:00,Not displayed,6954337960046817851BCB2,2007-01-17 00:00:00,Q1 2007,5F7033715035555618FA612
3,0EF5356002482715299901A,2012-10-22 11:02:35.010000000,C,Current,2014-03-04 00:00:00,A,GA,Skilled Labor,Employed,783C3371218786870A73D20,2012-10-22 11:02:32,1983-02-28 00:00:00,"$25,000-49,999",A0393664465886295619C51,2012-11-01 00:00:00,Q4 2012,9ADE356069835475068C6D2
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097000000,C,Current,2014-03-04 00:00:00,D,MN,Executive,Employed,783C3371218786870A73D20,2013-09-14 18:38:44,2004-02-20 00:00:00,"$100,000+",A180369302188889200689E,2013-09-20 00:00:00,Q3 2013,36CE356043264555721F06C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,E6D9357655724827169606C,2013-04-14 05:55:02.663000000,C,Current,2014-03-04 00:00:00,C,IL,Food Service Management,Employed,783C3371218786870A73D20,2013-04-14 05:54:58,1997-09-01 00:00:00,"$50,000-74,999",9BD7367919051593140DB62,2013-04-22 00:00:00,Q2 2013,2EC435768441332602FDC15
113933,E6DB353036033497292EE43,2011-11-03 20:42:55.333000000,C,FinalPaymentInProgress,2014-03-04 00:00:00,A,PA,Professional,Employed,783C3371218786870A73D20,2011-11-03 20:42:53,1992-01-17 00:00:00,"$75,000-99,999",62D93634569816897D5A276,2011-11-07 00:00:00,Q4 2011,55C4336679182766893E4FC
113934,E6E13596170052029692BB1,2013-12-13 05:49:12.703000000,C,Current,2014-03-04 00:00:00,D,TX,Other,Employed,783C3371218786870A73D20,2013-12-13 05:49:15,2002-02-25 00:00:00,"$25,000-49,999",DD1A370200396006300ACA0,2013-12-23 00:00:00,Q4 2013,0FE0370029359765342FDB5
113935,E6EB3531504622671970D9E,2011-11-14 13:18:26.597000000,C,Completed,2013-08-13 00:00:00,C,GA,Food Service,Full-time,783C3371218786870A73D20,2011-11-14 13:18:24,1993-12-01 00:00:00,"$25,000-49,999",589536350469116027ED11B,2011-11-21 00:00:00,Q4 2011,A33834861822272782621C8
113936,E6ED3600409833199F711B7,2014-01-15 09:27:37.657000000,C,Current,2014-03-04 00:00:00,A,NY,Professor,Employed,783C3371218786870A73D20,2014-01-15 09:27:40,1995-01-01 00:00:00,"$50,000-74,999",00AF3704550953269A64E40,2014-01-21 00:00:00,Q1 2014,CE1E3704648000761C9F724

In [14]:
categorical.isna().sum()

ListingKey                 0
ListingCreationDate        0
CreditGrade                0
LoanStatus                 0
ClosedDate                 0
ProsperRating (Alpha)      0
BorrowerState              0
Occupation                 0
EmploymentStatus           0
GroupKey                   0
DateCreditPulled           0
FirstRecordedCreditLine    0
IncomeRange                0
LoanKey                    0
LoanOriginationDate        0
LoanOriginationQuarter     0
MemberKey                  0
dtype: int64

All the missing values of categorical attributes are now filled.

Checking Missing (null) values of Numerical attributes:

In [15]:
continuous.isna().sum()

ListingNumber                   0
Term                            0
BorrowerAPR                    25
BorrowerRate                    0
LenderYield                     0
                               ..
PercentFunded                   0
Recommendations                 0
InvestmentFromFriendsCount      0
InvestmentFromFriendsAmount     0
Investors                       0
Length: 61, dtype: int64

#### Filling Missing values of Numerical attributes using Median funcion:

In [16]:
continuous=continuous.fillna(continuous.median().iloc[0])
continuous

,ListingNumber,Term,BorrowerAPR,BorrowerRate,LenderYield,EstimatedEffectiveYield,EstimatedLoss,EstimatedReturn,ProsperRating (numeric),ProsperScore,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,193129,36,0.16516,0.1580,0.1380,600554.00000,600554.0000,600554.00000,600554.0,600554.0,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,1209647,36,0.12016,0.0920,0.0820,0.07960,0.0249,0.05470,6.0,7.0,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,81716,36,0.28269,0.2750,0.2400,600554.00000,600554.0000,600554.00000,600554.0,600554.0,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,658116,36,0.12528,0.0974,0.0874,0.08490,0.0249,0.06000,6.0,9.0,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,909464,36,0.24614,0.2085,0.1985,0.18316,0.0925,0.09066,3.0,4.0,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,753087,36,0.22354,0.1864,0.1764,0.16490,0.0699,0.09500,4.0,5.0,...,-75.58,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
113933,537216,36,0.13220,0.1110,0.1010,0.10070,0.0200,0.08070,6.0,8.0,...,-30.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,22
113934,1069178,60,0.23984,0.2150,0.2050,0.18828,0.1025,0.08578,3.0,3.0,...,-16.91,0.0,0.0,0.0,0.0,1.0,0,0,0.0,119
113935,539056,60,0.28408,0.2605,0.2505,0.24450,0.0850,0.15950,4.0,5.0,...,-235.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,274
113936,1140093,36,0.13189,0.1039,0.0939,0.09071,0.0299,0.06081,6.0,7.0,...,-1.70,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

In [17]:
continuous.isna().sum()

ListingNumber                  0
Term                           0
BorrowerAPR                    0
BorrowerRate                   0
LenderYield                    0
                              ..
PercentFunded                  0
Recommendations                0
InvestmentFromFriendsCount     0
InvestmentFromFriendsAmount    0
Investors                      0
Length: 61, dtype: int64

All the missing values of Numerical attributes are now filled.

#### Combining the Categorical continuous data into one file named "ndf" using concat function with the inner join condition.

In [18]:
ndf=pd.concat([categorical,continuous],axis=1,join='inner')
ndf

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,...,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors
0,1021339766868145413AB3B,2007-08-26 19:09:29.263000000,C,Completed,2009-08-14 00:00:00,C,CO,Other,Self-employed,783C3371218786870A73D20,...,-133.18,0.0,0.0,0.0,0.0,1.0,0,0,0.0,258
1,10273602499503308B223C1,2014-02-27 08:28:07.900000000,C,Current,2014-03-04 00:00:00,A,CO,Professional,Employed,783C3371218786870A73D20,...,0.00,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
2,0EE9337825851032864889A,2007-01-05 15:00:47.090000000,HR,Completed,2009-12-17 00:00:00,C,GA,Other,Not available,783C3371218786870A73D20,...,-24.20,0.0,0.0,0.0,0.0,1.0,0,0,0.0,41
3,0EF5356002482715299901A,2012-10-22 11:02:35.010000000,C,Current,2014-03-04 00:00:00,A,GA,Skilled Labor,Employed,783C3371218786870A73D20,...,-108.01,0.0,0.0,0.0,0.0,1.0,0,0,0.0,158
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097000000,C,Current,2014-03-04 00:00:00,D,MN,Executive,Employed,783C3371218786870A73D20,...,-60.27,0.0,0.0,0.0,0.0,1.0,0,0,0.0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113932,E6D9357655724827169606C,2013-04-14 05:55:02.663000000,C,Current,2014-03-04 00:00:00,C,IL,Food Service Management,Employed,783C3371218786870A73D20,...,-75.58,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1
113933,E6DB353036033497292EE43,2011-11-03 20:42:55.333000000,C,FinalPaymentInProgress,2014-03-04 00:00:00,A,PA,Professional,Employed,783C3371218786870A73D20,...,-30.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,22
113934,E6E13596170052029692BB1,2013-12-13 05:49:12.703000000,C,Current,2014-03-04 00:00:00,D,TX,Other,Employed,783C3371218786870A73D20,...,-16.91,0.0,0.0,0.0,0.0,1.0,0,0,0.0,119
113935,E6EB3531504622671970D9E,2011-11-14 13:18:26.597000000,C,Completed,2013-08-13 00:00:00,C,GA,Food Service,Full-time,783C3371218786870A73D20,...,-235.05,0.0,0.0,0.0,0.0,1.0,0,0,0.0,274
113936,E6ED3600409833199F711B7,2014-01-15 09:27:37.657000000,C,Current,2014-03-04 00:00:00,A,NY,Professor,Employed,783C3371218786870A73D20,...,-1.70,0.0,0.0,0.0,0.0,1.0,0,0,0.0,1

Checking again wether there is still have missing values or not

In [19]:
ndf.isna().sum().value_counts()

0    78
dtype: int64

In [20]:
ndf.duplicated().sum()

0

In [21]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113937 entries, 0 to 113936
Data columns (total 78 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   ListingKey                           113937 non-null  object
 1   ListingCreationDate                  113937 non-null  object
 2   CreditGrade                          113937 non-null  object
 3   LoanStatus                           113937 non-null  object
 4   ClosedDate                           113937 non-null  object
 5   ProsperRating (Alpha)                113937 non-null  object
 6   BorrowerState                        113937 non-null  object
 7   Occupation                           113937 non-null  object
 8   EmploymentStatus                     113937 non-null  object
 9   GroupKey                             113937 non-null  object
 10  DateCreditPulled                     113937 non-null  object
 11  FirstRecordedCreditLine              113937 non-null  object
 12  IncomeRange                          113937 non-null  object
 13  LoanKey                              113937 non-null  object
 14  LoanOriginationDate                  113937 non-null  object
 15  LoanOriginationQuarter               113937 non-null  object
 16  MemberKey                            113937 non-null  object
 17  ListingNumber                        113937 non-null  int64
 18  Term                                 113937 non-null  int64
 19  BorrowerAPR                          113937 non-null  float64
 20  BorrowerRate                         113937 non-null  float64
 21  LenderYield                          113937 non-null  float64
 22  EstimatedEffectiveYield              113937 non-null  float64
 23  EstimatedLoss                        113937 non-null  float64
 24  EstimatedReturn                      113937 non-null  float64
 25  ProsperRating (numeric)              113937 non-null  float64
 26  ProsperScore                         113937 non-null  float64
 27  ListingCategory (numeric)            113937 non-null  int64
 28  EmploymentStatusDuration             113937 non-null  float64
 29  CreditScoreRangeLower                113937 non-null  float64
 30  CreditScoreRangeUpper                113937 non-null  float64
 31  CurrentCreditLines                   113937 non-null  float64
 32  OpenCreditLines                      113937 non-null  float64
 33  TotalCreditLinespast7years           113937 non-null  float64
 34  OpenRevolvingAccounts                113937 non-null  int64
 35  OpenRevolvingMonthlyPayment          113937 non-null  float64
 36  InquiriesLast6Months                 113937 non-null  float64
 37  TotalInquiries                       113937 non-null  float64
 38  CurrentDelinquencies                 113937 non-null  float64
 39  AmountDelinquent                     113937 non-null  float64
 40  DelinquenciesLast7Years              113937 non-null  float64
 41  PublicRecordsLast10Years             113937 non-null  float64
 42  PublicRecordsLast12Months            113937 non-null  float64
 43  RevolvingCreditBalance               113937 non-null  float64
 44  BankcardUtilization                  113937 non-null  float64
 45  AvailableBankcardCredit              113937 non-null  float64
 46  TotalTrades                          113937 non-null  float64
 47  TradesNeverDelinquent (percentage)   113937 non-null  float64
 48  TradesOpenedLast6Months              113937 non-null  float64
 49  DebtToIncomeRatio                    113937 non-null  float64
 50  StatedMonthlyIncome                  113937 non-null  float64
 51  TotalProsperLoans                    113937 non-null  float64
 52  TotalProsperPaymentsBilled           113937 non-null  float64
 53  OnTimeProsperPayments                113937 non-null  float64
 54  ProsperPaymentsLessThanOneMonthLate  113937 non-null  float64
 55  ProsperPaymentsOneMonthPlusLate      113937 non-null  float64
 56  ProsperPrincipalBorrowed             113937 non-null  float64
 57  ProsperPrincipalOutstanding          113937 non-null  float64
 58  ScorexChangeAtTimeOfListing          113937 non-null  float64
 59  LoanCurrentDaysDelinquent            113937 non-null  int64
 60  LoanFirstDefaultedCycleNumber        113937 non-null  float64
 61  LoanMonthsSinceOrigination           113937 non-null  int64
 62  LoanNumber                           113937 non-null  int64
 63  LoanOriginalAmount                   113937 non-null  int64
 64  MonthlyLoanPayment                   113937 non-null  float64
 65  LP_CustomerPayments                  113937 non-null  float64
 66  LP_CustomerPrincipalPayments         113937 non-null  float64
 67  LP_InterestandFees                   113937 non-null  float64
 68  LP_ServiceFees                       113937 non-null  float64
 69  LP_CollectionFees                    113937 non-null  float64
 70  LP_GrossPrincipalLoss                113937 non-null  float64
 71  LP_NetPrincipalLoss                  113937 non-null  float64
 72  LP_NonPrincipalRecoverypayments      113937 non-null  float64
 73  PercentFunded                        113937 non-null  float64
 74  Recommendations                      113937 non-null  int64
 75  InvestmentFromFriendsCount           113937 non-null  int64
 76  InvestmentFromFriendsAmount          113937 non-null  float64
 77  Investors                            113937 non-null  int64
dtypes: float64(50), int64(11), object(17)
memory usage: 67.8+ MB

### Implementing the Model Formulae

#### Loan Tenure:

In [22]:
ndf["Term"].describe()

count    113937.000000
mean         40.830248
std          10.436212
min          12.000000
25%          36.000000
50%          36.000000
75%          36.000000
max          60.000000
Name: Term, dtype: float64

In [23]:
ndf["ClosedDate"]=pd.to_datetime(ndf["ClosedDate"])
ndf["LoanOriginationDate"]=pd.to_datetime(ndf["LoanOriginationDate"])
ndf["ListingCreationDate"]=pd.to_datetime(ndf["ListingCreationDate"])

#### LoanTenure = (𝑀𝑎𝑡𝑢𝑟𝑖𝑡𝑦𝐷𝑎𝑡e_𝑂𝑟𝑖𝑔𝑖𝑛𝑎𝑙𝑦𝑒𝑎𝑟 − 𝐿𝑜𝑎𝑛𝐷𝑎𝑡𝑒𝑦𝑒𝑎𝑟) 𝑥 12 − (𝑀𝑎𝑡𝑢𝑟𝑖𝑡𝑦𝐷𝑎𝑡𝑒_𝑂𝑟𝑖𝑔𝑖𝑛𝑎𝑙𝑚𝑜𝑛𝑡ℎ − 𝐿𝑜𝑎𝑛𝐷𝑎𝑡𝑒𝑚𝑜𝑛𝑡ℎ)

In [24]:
ndf["LoanTenure"]=((ndf["ClosedDate"].dt.year-ndf["LoanOriginationDate"].dt.year)*12)-(ndf["ClosedDate"].dt.month-ndf["LoanOriginationDate"].dt.month)

In [25]:
ndf["LoanTenure"].describe()

count    113937.000000
mean         18.276205
std          13.171577
min         -27.000000
25%          11.000000
50%          18.000000
75%          28.000000
max          59.000000
Name: LoanTenure, dtype: float64

#### Equated Monthly Installments (EMI):

Tenure ---> **LoanTenure**
Principle repayment ---> **LP_CustomerPrinciplePayments**
Interest ---> **BorrowerRate**

In [26]:
def calculate_emi(LP_CustomerPrincipalPayments,BorrowerRate,LoanTenure):
    monthly_interst_rate = BorrowerRate/12/100
    emi = ((LP_CustomerPrincipalPayments*monthly_interst_rate*(1+monthly_interst_rate)**(LoanTenure))/((1+monthly_interst_rate)**(LoanTenure-1)))
    
    return emi

In [27]:
ndf["EMI"]= calculate_emi(ndf["LP_CustomerPrincipalPayments"],ndf["BorrowerRate"],ndf["LoanTenure"])

In [28]:
ndf["EMI"]

0         1.241122
1         0.000000
2         0.687887
3         0.332087
4         0.271657
            ...
113932    0.347749
113933    0.184754
113934    0.032820
113935    3.256957
113936    0.004091
Name: EMI, Length: 113937, dtype: float64

In [29]:
ndf["EMI"].describe()

count    113937.000000
mean          0.459939
std           0.596668
min           0.000000
25%           0.074731
50%           0.234060
75%           0.607737
max           7.318697
Name: EMI, dtype: float64

#### Preferred Return on Investment (PROI):

In [30]:
def calculated_roi():
    ndf['InterestAmount']=(ndf['LoanOriginalAmount']*(ndf["BorrowerRate"]))
    ndf["TotalAmount"]=(ndf["InterestAmount"]+ndf["LoanOriginalAmount"])
    ndf["ROI"]=(ndf["InterestAmount"]/ndf["TotalAmount"])
    return ndf["ROI"]
#ndf.drop(['InterestAmount'],axis=1,inplace=True)
#ndf.drop(["TotalAmount"],axis=1,inplace=True)

In [31]:
ndf["ROI"]=calculated_roi()

In [32]:
ndf["ROI"].describe()

count    113937.000000
mean          0.158343
std           0.052204
min           0.000000
25%           0.118166
50%           0.155405
75%           0.200000
max           0.332220
Name: ROI, dtype: float64

In [33]:
ndf.head()

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,...,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors,LoanTenure,EMI,InterestAmount,TotalAmount,ROI
0,1021339766868145413AB3B,2007-08-26 19:09:29.263,C,Completed,2009-08-14,C,CO,Other,Self-employed,783C3371218786870A73D20,...,1.0,0,0,0.0,258,25,1.241122,1489.150,10914.150,0.136442
1,10273602499503308B223C1,2014-02-27 08:28:07.900,C,Current,2014-03-04,A,CO,Professional,Employed,783C3371218786870A73D20,...,1.0,0,0,0.0,1,0,0.000000,920.000,10920.000,0.084249
2,0EE9337825851032864889A,2007-01-05 15:00:47.090,HR,Completed,2009-12-17,C,GA,Other,Not available,783C3371218786870A73D20,...,1.0,0,0,0.0,41,13,0.687887,825.275,3826.275,0.215686
3,0EF5356002482715299901A,2012-10-22 11:02:35.010,C,Current,2014-03-04,A,GA,Skilled Labor,Employed,783C3371218786870A73D20,...,1.0,0,0,0.0,158,32,0.332087,974.000,10974.000,0.088755
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097,C,Current,2014-03-04,D,MN,Executive,Employed,783C3371218786870A73D20,...,1.0,0,0,0.0,20,18,0.271657,3127.500,18127.500,0.172528

In [34]:
ndf.drop(['InterestAmount'],axis=1,inplace=True)
ndf.drop(["TotalAmount"],axis=1,inplace=True)

In [35]:
ndf.head()

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,...,LP_NetPrincipalLoss,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors,LoanTenure,EMI,ROI
0,1021339766868145413AB3B,2007-08-26 19:09:29.263,C,Completed,2009-08-14,C,CO,Other,Self-employed,783C3371218786870A73D20,...,0.0,0.0,1.0,0,0,0.0,258,25,1.241122,0.136442
1,10273602499503308B223C1,2014-02-27 08:28:07.900,C,Current,2014-03-04,A,CO,Professional,Employed,783C3371218786870A73D20,...,0.0,0.0,1.0,0,0,0.0,1,0,0.000000,0.084249
2,0EE9337825851032864889A,2007-01-05 15:00:47.090,HR,Completed,2009-12-17,C,GA,Other,Not available,783C3371218786870A73D20,...,0.0,0.0,1.0,0,0,0.0,41,13,0.687887,0.215686
3,0EF5356002482715299901A,2012-10-22 11:02:35.010,C,Current,2014-03-04,A,GA,Skilled Labor,Employed,783C3371218786870A73D20,...,0.0,0.0,1.0,0,0,0.0,158,32,0.332087,0.088755
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097,C,Current,2014-03-04,D,MN,Executive,Employed,783C3371218786870A73D20,...,0.0,0.0,1.0,0,0,0.0,20,18,0.271657,0.172528

#### Eligible Loan Amount (ELA):

Components of ELA:

A: “AppliedAmount” ---> LoanOriginalAmount
R: “Interest” ---> BorrowerRate
N: “LoanTenure” ---> LoanTenure
I: “IncomeTotal” ---> StatedMonthlyIncome

Calculation Procedure: For each row in the dataset:

Calculate: Total Payment Due = (A + (A*r)) * n
Calculate: Max allowable amount = I * 12 * 30%
If ( Total Payment Due <= Max allowable amount)
  Then ELA = AppliedAmount
  Else ELA = Max allowable amount

In [36]:

def eligible_loan_amount():
    ndf["Avg_Inc"]=(ndf["StatedMonthlyIncome"]*12*0.3)*ndf["LoanTenure"]
    ndf["Total_Loan_Amount"]=np.round(ndf["LoanOriginalAmount"]+(ndf["LoanOriginalAmount"]*ndf["BorrowerRate"])*ndf["LoanTenure"])
    ELA=np.empty(0)
    for i in range(len(ndf["Avg_Inc"].values)):
        if ndf["Avg_Inc"].iloc[i]<=0:
            ELA = np.append(ELA,0)
        elif ndf["Total_Loan_Amount"].iloc[i]<=ndf["Avg_Inc"].iloc[i]:
            ELA = np.append(ELA,ndf["Total_Loan_Amount"].iloc[i])
        else :
            ELA = np.append(ELA,ndf["Avg_Inc"].iloc[i])
    ndf.drop(["Avg_Inc"],axis=1,inplace=True)
    ndf.drop(["Total_Loan_Amount"],axis=1,inplace=True)
    return ELA

In [37]:
ndf["ELA"]=eligible_loan_amount()
ndf["ELA"].describe()

count    113937.000000
mean      31937.410300
std       31189.934931
min           0.000000
25%        8585.000000
50%       24103.000000
75%       46304.000000
max      392500.000000
Name: ELA, dtype: float64

In [38]:
ndf.head()

,ListingKey,ListingCreationDate,CreditGrade,LoanStatus,ClosedDate,ProsperRating (Alpha),BorrowerState,Occupation,EmploymentStatus,GroupKey,...,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors,LoanTenure,EMI,ROI,ELA
0,1021339766868145413AB3B,2007-08-26 19:09:29.263,C,Completed,2009-08-14,C,CO,Other,Self-employed,783C3371218786870A73D20,...,0.0,1.0,0,0,0.0,258,25,1.241122,0.136442,46654.0
1,10273602499503308B223C1,2014-02-27 08:28:07.900,C,Current,2014-03-04,A,CO,Professional,Employed,783C3371218786870A73D20,...,0.0,1.0,0,0,0.0,1,0,0.000000,0.084249,0.0
2,0EE9337825851032864889A,2007-01-05 15:00:47.090,HR,Completed,2009-12-17,C,GA,Other,Not available,783C3371218786870A73D20,...,0.0,1.0,0,0,0.0,41,13,0.687887,0.215686,13730.0
3,0EF5356002482715299901A,2012-10-22 11:02:35.010,C,Current,2014-03-04,A,GA,Skilled Labor,Employed,783C3371218786870A73D20,...,0.0,1.0,0,0,0.0,158,32,0.332087,0.088755,41168.0
4,0F023589499656230C5E3E2,2013-09-14 18:38:39.097,C,Current,2014-03-04,D,MN,Executive,Employed,783C3371218786870A73D20,...,0.0,1.0,0,0,0.0,20,18,0.271657,0.172528,71295.0

### Removing unnecessary columns from the dataset

In [39]:
ndf.drop(['ListingKey',"ListingCreationDate",'ClosedDate',"BorrowerState","ProsperRating (Alpha)",'FirstRecordedCreditLine','IncomeRange','LoanStatus','Term','ListingCreationDate','LoanOriginationDate','GroupKey','ProsperPrincipalBorrowed','ProsperPrincipalOutstanding','EstimatedEffectiveYield','EstimatedLoss','EstimatedReturn','ProsperRating (numeric)','TotalProsperLoans','TotalProsperPaymentsBilled','OnTimeProsperPayments','ProsperPaymentsLessThanOneMonthLate','ProsperPaymentsOneMonthPlusLate','ListingKey','ListingCategory (numeric)','Occupation','DateCreditPulled','LoanKey','LoanOriginationQuarter','ListingNumber','MemberKey'],axis=1,inplace=True)

In [40]:
ndf.columns

Index(['CreditGrade', 'EmploymentStatus', 'BorrowerAPR', 'BorrowerRate',
       'LenderYield', 'ProsperScore', 'EmploymentStatusDuration',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper', 'CurrentCreditLines',
       'OpenCreditLines', 'TotalCreditLinespast7years',
       'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment',
       'InquiriesLast6Months', 'TotalInquiries', 'CurrentDelinquencies',
       'AmountDelinquent', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'RevolvingCreditBalance', 'BankcardUtilization',
       'AvailableBankcardCredit', 'TotalTrades',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'DebtToIncomeRatio', 'StatedMonthlyIncome',
       'ScorexChangeAtTimeOfListing', 'LoanCurrentDaysDelinquent',
       'LoanFirstDefaultedCycleNumber', 'LoanMonthsSinceOrigination',
       'LoanNumber', 'LoanOriginalAmount', 'MonthlyLoanPayment',
       'LP_CustomerPayments', 'LP_CustomerPrincipalPayments',
       'LP_InterestandFees', 'LP_ServiceFees', 'LP_CollectionFees',
       'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'InvestmentFromFriendsAmount',
       'Investors', 'LoanTenure', 'EMI', 'ROI', 'ELA'],
      dtype='object')

In [41]:
ndf.head()

,CreditGrade,EmploymentStatus,BorrowerAPR,BorrowerRate,LenderYield,ProsperScore,EmploymentStatusDuration,CreditScoreRangeLower,CreditScoreRangeUpper,CurrentCreditLines,...,LP_NonPrincipalRecoverypayments,PercentFunded,Recommendations,InvestmentFromFriendsCount,InvestmentFromFriendsAmount,Investors,LoanTenure,EMI,ROI,ELA
0,C,Self-employed,0.16516,0.1580,0.1380,600554.0,2.0,640.0,659.0,5.0,...,0.0,1.0,0,0,0.0,258,25,1.241122,0.136442,46654.0
1,C,Employed,0.12016,0.0920,0.0820,7.0,44.0,680.0,699.0,14.0,...,0.0,1.0,0,0,0.0,1,0,0.000000,0.084249,0.0
2,HR,Not available,0.28269,0.2750,0.2400,600554.0,600554.0,480.0,499.0,600554.0,...,0.0,1.0,0,0,0.0,41,13,0.687887,0.215686,13730.0
3,C,Employed,0.12528,0.0974,0.0874,9.0,113.0,800.0,819.0,5.0,...,0.0,1.0,0,0,0.0,158,32,0.332087,0.088755,41168.0
4,C,Employed,0.24614,0.2085,0.1985,4.0,44.0,680.0,699.0,19.0,...,0.0,1.0,0,0,0.0,20,18,0.271657,0.172528,71295.0

In [42]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
ndf['CreditGrade']= label_encoder.fit_transform(ndf['CreditGrade'])

In [43]:
ndf.columns

Index(['CreditGrade', 'EmploymentStatus', 'BorrowerAPR', 'BorrowerRate',
       'LenderYield', 'ProsperScore', 'EmploymentStatusDuration',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper', 'CurrentCreditLines',
       'OpenCreditLines', 'TotalCreditLinespast7years',
       'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment',
       'InquiriesLast6Months', 'TotalInquiries', 'CurrentDelinquencies',
       'AmountDelinquent', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'RevolvingCreditBalance', 'BankcardUtilization',
       'AvailableBankcardCredit', 'TotalTrades',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'DebtToIncomeRatio', 'StatedMonthlyIncome',
       'ScorexChangeAtTimeOfListing', 'LoanCurrentDaysDelinquent',
       'LoanFirstDefaultedCycleNumber', 'LoanMonthsSinceOrigination',
       'LoanNumber', 'LoanOriginalAmount', 'MonthlyLoanPayment',
       'LP_CustomerPayments', 'LP_CustomerPrincipalPayments',
       'LP_InterestandFees', 'LP_ServiceFees', 'LP_CollectionFees',
       'LP_GrossPrincipalLoss', 'LP_NetPrincipalLoss',
       'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'InvestmentFromFriendsAmount',
       'Investors', 'LoanTenure', 'EMI', 'ROI', 'ELA'],
      dtype='object')

In [44]:
ndf.drop(['EmploymentStatus'],axis=1,inplace=True)

### Feature Engineering :

#### Splitting data into Training and Testing data

In [45]:
X=ndf.iloc[:,:-3]
Y=ndf.iloc[:,-3:]

In [46]:
X.drop(['EmploymentStatusDuration',
       'CreditScoreRangeLower', 'CreditScoreRangeUpper', 'CurrentCreditLines',
       'OpenCreditLines', 'TotalCreditLinespast7years',
       'OpenRevolvingAccounts', 'OpenRevolvingMonthlyPayment',
       'InquiriesLast6Months', 'TotalInquiries', 'CurrentDelinquencies',
       'AmountDelinquent', 'DelinquenciesLast7Years',
       'PublicRecordsLast10Years', 'PublicRecordsLast12Months',
       'RevolvingCreditBalance', 'BankcardUtilization','AvailableBankcardCredit', 'TotalTrades',
       'TradesNeverDelinquent (percentage)', 'TradesOpenedLast6Months',
       'DebtToIncomeRatio','ScorexChangeAtTimeOfListing', 'LoanCurrentDaysDelinquent',
       'LoanFirstDefaultedCycleNumber', 'LoanMonthsSinceOrigination',
       'LoanNumber', 'LP_NonPrincipalRecoverypayments', 'PercentFunded', 'Recommendations',
       'InvestmentFromFriendsCount', 'InvestmentFromFriendsAmount',
       'Investors','LP_NetPrincipalLoss'],axis=1,inplace=True)

In [47]:
X.shape

(113937, 15)

In [48]:
X.columns

Index(['CreditGrade', 'BorrowerAPR', 'BorrowerRate', 'LenderYield',
       'ProsperScore', 'StatedMonthlyIncome', 'LoanOriginalAmount',
       'MonthlyLoanPayment', 'LP_CustomerPayments',
       'LP_CustomerPrincipalPayments', 'LP_InterestandFees', 'LP_ServiceFees',
       'LP_CollectionFees', 'LP_GrossPrincipalLoss', 'LoanTenure'],
      dtype='object')

In [49]:
Y

             EMI       ROI       ELA
0       1.241122  0.136442   46654.0
1       0.000000  0.084249       0.0
2       0.687887  0.215686   13730.0
3       0.332087  0.088755   41168.0
4       0.271657  0.172528   71295.0
...          ...       ...       ...
113932  0.347749  0.157114   34232.0
113933  0.184754  0.099910   11768.0
113934  0.032820  0.176955   55150.0
113935  3.256957  0.206664  120502.0
113936  0.004091  0.094121       0.0

[113937 rows x 3 columns]

Splitting the data

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.20 , random_state = 100)

### Model Fitting

#### Linear Regression

In [51]:
from sklearn.linear_model import LinearRegression
LR_model = LinearRegression()
LR_model.fit(X_train,Y_train)

LinearRegression()

In [52]:
X_test.head()

,CreditGrade,BorrowerAPR,BorrowerRate,LenderYield,ProsperScore,StatedMonthlyIncome,LoanOriginalAmount,MonthlyLoanPayment,LP_CustomerPayments,LP_CustomerPrincipalPayments,LP_InterestandFees,LP_ServiceFees,LP_CollectionFees,LP_GrossPrincipalLoss,LoanTenure
29253,3,0.13138,0.1034,0.0934,8.0,5833.333333,10000,324.27,4539.78,3524.71,1015.07,-98.16,0.0,0.00,33
82732,3,0.38723,0.3500,0.3400,3.0,7500.000000,3500,158.33,5653.93,3500.00,2153.93,-61.55,0.0,0.00,40
14796,3,0.28032,0.2419,0.2319,4.0,3500.000000,6000,236.00,1416.00,720.22,695.78,-28.76,0.0,0.00,17
103448,6,0.30377,0.2875,0.2825,600554.0,1759.333333,1200,50.12,380.96,154.92,226.04,-3.93,0.0,1045.07,11
99191,3,0.27246,0.2468,0.2368,7.0,953.500000,13000,379.13,8340.86,3054.80,5286.06,-214.16,0.0,0.00,25

Predicting the values using Linear regression model

In [53]:
Y_pred=LR_model.predict(X_test)

In [54]:
Y_pred[:5]

array([[ 2.46607099e-01,  9.59411159e-02,  4.72477196e+04],
       [ 8.97736904e-01,  2.67406491e-01,  6.17333557e+04],
       [ 2.29253627e-01,  1.92261313e-01,  2.55102622e+04],
       [ 1.51854645e-01,  2.24147665e-01, -1.45814390e+03],
       [ 8.97706958e-01,  1.98193292e-01,  1.00862971e+05]])

In [55]:
Y_test[:5]

             EMI       ROI      ELA
29253   0.303739  0.093710  44122.0
82732   1.021131  0.259259  52500.0
14796   0.145214  0.194782  30674.0
103448  0.037125  0.223301   4995.0
99191   0.628400  0.197947  85815.0

In [56]:
from sklearn import metrics

In [57]:
print('MSE:', metrics.mean_squared_error(Y_test, Y_pred))
print('MAE:', metrics.mean_absolute_error(Y_test, Y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

MSE: 64179797.601055145
MAE: 3199.473995791461
RMSE: 8011.229468755413

In [58]:
from sklearn.metrics import r2_score
r2= r2_score(Y_test,Y_pred)
print("R2 score:", r2)

R2 score: 0.9018610158720929

#### The model achieved an R-squared(R2) value of 90%

### Ridge Regression

In [59]:
from sklearn.linear_model import Ridge
Ridge_classifier = Ridge(alpha=1.0)
Ridge_classifier.fit(X_train,Y_train)

Ridge()

Predicting the values using Ridge regression model

In [60]:
Y_pred=Ridge_classifier.predict(X_test)

In [61]:
print('MSE:', metrics.mean_squared_error(Y_test, Y_pred))
print('MAE:', metrics.mean_absolute_error(Y_test, Y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

MSE: 64181255.4675098
MAE: 3200.3522520874626
RMSE: 8011.32045717245

In [62]:
from sklearn.metrics import r2_score
r2= r2_score(Y_test,Y_pred)
print("R2 score:", r2)

R2 score: 0.9014009009370403

#### The model achieved an R-squared(R2) value of 90%

## Pipeline

### Pipeline for Linear Regression

In [63]:
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE 
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

from sklearn import set_config

In [64]:
scaler=StandardScaler()
LR_model = LinearRegression()

In [65]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=100)

* Pipeline Creation

In [66]:
linear_regression_pipeline=Pipeline([
    ("sclaer",scaler),
    ("LR_model",LR_model)
])

In [67]:
# fitting the training values 

linear_regression_pipeline.fit(X_train,Y_train)

Pipeline(steps=[('sclaer', StandardScaler()), ('LR_model', LinearRegression())])

In [68]:
Y_pred=linear_regression_pipeline.predict(X_test)
Y_pred[:5]

array([[ 2.47641171e-01,  9.59444310e-02,  4.72144316e+04],
       [ 8.95880583e-01,  2.67334221e-01,  6.20044059e+04],
       [ 2.30048697e-01,  1.92303985e-01,  2.54292492e+04],
       [ 1.52311788e-01,  2.24159593e-01, -1.48747316e+03],
       [ 8.98384224e-01,  1.98291366e-01,  1.00500208e+05]])

In [69]:
from sklearn.metrics import r2_score
r2= r2_score(Y_test,Y_pred)
print("R2 score:", r2)

R2 score: 0.9024540074964982

In [70]:
print('MSE:', metrics.mean_squared_error(Y_test, Y_pred))
print('MAE:', metrics.mean_absolute_error(Y_test, Y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

MSE: 64212293.336829536
MAE: 3184.365684263696
RMSE: 8013.257348720902

### Key poits
**R2 score: 0.9045155164676496** <br>
**MSE: 62317399.64700652** <br>
**MAE: 3134.6106135593222** <br>
**RMSE: 7894.137042578278**

### Pipeline for Ridge Regression

In [71]:
Ridge_regression_pipeline=Pipeline([
    ("sclaer",scaler),
    ("Ridge_model",Ridge_classifier)
])

In [72]:
Ridge_regression_pipeline.fit(X_train,Y_train)

Pipeline(steps=[('sclaer', StandardScaler()), ('Ridge_model', Ridge())])

In [73]:
Y_predict=Ridge_regression_pipeline.predict(X_test)

In [74]:
r2= r2_score(Y_test,Y_predict)
print("R2 score:", r2)

R2 score: 0.9024537484286409

In [75]:
print('MSE:', metrics.mean_squared_error(Y_test, Y_pred))
print('MAE:', metrics.mean_absolute_error(Y_test, Y_pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

MSE: 64212293.336829536
MAE: 3184.365684263696
RMSE: 8013.257348720902

In [76]:
import joblib

joblib.dump(Ridge_regression_pipeline,"ridge_model.joblib")

['ridge_model.joblib']

### Key poits
**R2 score: 0.9045154701154257** <br>
**MSE: 62317399.64700652** <br>
**MAE: 3134.6106135593222** <br>
**RMSE: 7894.137042578278**

## Final Pipeline for Regression Models

In [77]:
from sklearn.ensemble import StackingRegressor
from sklearn.multioutput import MultiOutputRegressor

In [78]:
from sklearn.ensemble import GradientBoostingRegressor

In [79]:
estimators = [('Ridge', Ridge_classifier), ('Linear', LR_model)]
final_estimator = GradientBoostingRegressor()
reg = StackingRegressor(estimators=estimators, final_estimator=final_estimator)
multioutput_reg = MultiOutputRegressor(reg)

In [80]:
multioutput_reg

MultiOutputRegressor(estimator=StackingRegressor(estimators=[('Ridge', Ridge()),
                                                             ('Linear',
                                                              LinearRegression())],
                                                 final_estimator=GradientBoostingRegressor()))

In [81]:
model_reg = Pipeline([
    ('scaler', scaler),
    ('regressor',multioutput_reg )
])

In [82]:
model_reg.fit(X_train,Y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('regressor',
                 MultiOutputRegressor(estimator=StackingRegressor(estimators=[('Ridge',
                                                                               Ridge()),
                                                                              ('Linear',
                                                                               LinearRegression())],
                                                                  final_estimator=GradientBoostingRegressor())))])

In [83]:
pred = model_reg.predict(X_test)
print('test accuracy = ', round(r2_score(Y_test, pred)*100, 2), '%')

test accuracy =  91.43 %

In [84]:
mae = round(metrics.mean_absolute_error(Y_test, pred),2)
mse = round(metrics.mean_squared_error(Y_test, pred),2)
print(f" Mean Absolute Error: {mae}\n")
print(f" Mean Squared Error: {mse}\n")

 Mean Absolute Error: 2799.57

 Mean Squared Error: 56745077.11

### Key Points

***Accuracy : 91.73 %*** <br>
***Mean Absolute Error: 2749.66***<br>
***Mean Squared Error: 53952023.05***

## Creating a pickle file of Final Regression Model

* Importing pickle file

In [85]:
import pickle as pkl

In [86]:
pkl.dump(model_reg,open("Regression_model_final.pkl","wb"))

### The multi regression model pipeline is converted into pickle file and dumped with the name as "Regression_model_final"

In [87]:
pip install joblib

Requirement already satisfied: joblib in f:\prodigy_infotech_task1\env\lib\site-packages (1.2.0)Note: you may need to restart the kernel to use updated packages.

In [88]:
import joblib

joblib.dump(model_reg,"regression_model.joblib")

['regression_model.joblib']